### ISSUE TITLE
OSM offline

### ISSUE THREAD

**Issue by rhespanhol** [johnjohndoe/OSMDroidOfflineDemo#2]
Hi, thanks for this demo.

Do you know if this still works? Im using your code and i cant make it work. I have tried with the zip file and putting the tiles folder in SDcard but nothing works.

Cheers

**Comment by johnjohndoe** [comment]
@rhespanhol I might have time in a few days to look into this.

**Comment by rhespanhol** [comment]
Sorry to bother you. Right now i was able to make it work. The problem is that MOBAC exports the tiles.zip file with a folder inside called MapQuest that is different from the tileprovider.


<code>
    public static final OnlineTileSourceBase MAPQUESTOSM = new XYTileSource("MapQuest",
            ResourceProxy.string.mapquest_osm, 0, 18, 256, ".jpg", new String[] {
            "http://otile1.mqcdn.com/tiles/1.0.0/map/",
            "http://otile2.mqcdn.com/tiles/1.0.0/map/",
            "http://otile3.mqcdn.com/tiles/1.0.0/map/",
            "http://otile4.mqcdn.com/tiles/1.0.0/map/" });
</code>

and use this new tilesource

<code>
mapView.setTileSource(MAPQUESTOSM);
</code>

**Comment by johnjohndoe** [comment]
Thanks for documenting this.
