### ISSUE TITLE
Maps are displayed repeatedly

### ISSUE THREAD

**Issue by alicewang05** [johnjohndoe/OSMDroidOfflineDemo#3]
Hello,
I have tried this demo. I am using osmdroid 4.2 instead of 4.2-snapshot as gradle could not find 4.2-snapshot.
I got so many maps displays at the same time. I set the min and max zoom level, also setScrollableAreaLimit(), but still does not work.
I also tried using MBtiles, still having the same issue.
Any idea to fix this, thanks a lot.
Best Reagrads,
Alice
![demo](https://cloud.githubusercontent.com/assets/12249700/9248847/5f21a040-41b7-11e5-807c-af6536bec77b.png)

**Comment by johnjohndoe** [comment]
I updated and tested the project on my device. I could not reproduce your issue. Please try again. Please also mind that this is just a demo application not a production ready application.

**Comment by alicewang05** [comment]
Hello, 
Thanks for your response.
I also contacted osmdroid about this issue, they do not think there is a way to fix it. 
https://github.com/osmdroid/osmdroid/issues/152#issuecomment-131772574
Cheers,
Alice

**Comment by johnjohndoe** [comment]
Okay. Thanks for the notice.
